name: Github action
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step1.1
        uses: browser-actions/setup-chrome@v2
        with: 
           chrome-version: 144.0.7559.109
           install-chromedriver: true
           install-dependencies: true          
      - name: setup
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: step3               
        run: mvn clean test --file pom.xml
      - name: step4
        run:
          cd target
          ls -a    
        
